[project]
name = "portkey"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "rahulbisht54367", email = "rahul.bisht@telgoo5.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "langchain-openai>=1.6.3",
    "langgraph>=1.2.12",
    "portkey-ai>=2.3.4",
    "pydantic-settings>=2.15.0",
]

[project.scripts]
portkey = "portkey:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
